- name: RHEL | Set version specific variables
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  tags:
    - always

- name: RHEL | Install Packages
  yum:
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      - python2-rpm
      - python-firewall
      - python-yumdaemon
      - libselinux-python
      - "{{ firewall_name }}"
    state: present
  tags:
    - common

- name: RHEL | Start firewalld
  service:
    name: "{{ firewalld_service }}"
    state: started

- name: RHEL | Enable specific firewall services
  firewalld:
    immediate: yes
    permanent: yes
    port: "{{ item.port ~ '/' ~ item.protocol if (item.port is defined and item.protocol is defined) else omit }}"
    service: "{{ item.service | default(omit) }}"
    state: enabled
  with_items: "{{ firewall_rules }}"
  notify: restart firewalld
